### ISSUE TITLE
please update extension for behat 3.0

### ISSUE THREAD

**Issue by cordoval** [M6Web/behat-seo-extension#9]

**Comment by sswarupa2017** [comment]
Is this extension available for Behat 3.0 ?

**Comment by sswarupa2017** [comment]
Is this extension available for behat 3.0? I see that it is closed but unable to install it and get the message:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - behat/mink-extension v1.3.1 requires behat/mink >=1.4.3,<1.6-dev -> satisfiable by behat/mink[v1.4.3, v1.5.0] but these conflict with your requirements or minimum-stability.
    - behat/mink-extension v1.3.0 requires behat/mink >=1.4.3,<1.6-dev -> satisfiable by behat/mink[v1.4.3, v1.5.0] but these conflict with your requirements or minimum-stability.
    - behat/mink-extension v1.2.0 requires behat/mink >=1.4.3,<1.6-dev -> satisfiable by behat/mink[v1.4.3, v1.5.0] but these conflict with your requirements or minimum-stability.
    - behat/mink-extension v1.1.4 requires behat/mink >=1.4.3,<1.6-dev -> satisfiable by behat/mink[v1.4.3, v1.5.0] but these conflict with your requirements or minimum-stability.
    - behat/mink-extension v1.1.3 requires behat/mink >=1.4.3,<1.6-dev -> satisfiable by behat/mink[v1.4.3, v1.5.0] but these conflict with your requirements or minimum-stability.
    - behat/mink-extension v1.1.2 requires behat/mink >=1.4.3,<1.6-dev -> satisfiable by behat/mink[v1.4.3, v1.5.0] but these conflict with your requirements or minimum-stability.
    - behat/mink-extension v1.1.1 requires behat/mink >=1.4.3,<1.6-dev -> satisfiable by behat/mink[v1.4.3, v1.5.0] but these conflict with your requirements or minimum-stability.
    - behat/mink-extension v1.1.0 requires behat/mink >=1.4.3,<1.6-dev -> satisfiable by behat/mink[v1.4.3, v1.5.0] but these conflict with your requirements or minimum-stability.
    - behat/mink-extension 1.2.x-dev requires behat/mink >=1.4.3,<1.6-dev -> satisfiable by behat/mink[v1.4.3, v1.5.0] but these conflict with your requirements or minimum-stability.

    - Installation request for m6web/seo-behat-extension master -> satisfiable by m6web/seo-behat-extension[dev-master].
    - m6web/seo-behat-extension dev-master requires behat/mink-extension ~1.1 -> satisfiable by behat/mink-extension[1.2.x-dev, 1.3.x-dev, v1.1.0, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.2.0, v1.3.0, v1.3.1, v1.3.2, v1.3.3].
    - behat/mink-extension 1.3.x-dev requires behat/behat ~2.5.0 -> satisfiable by behat/behat[2.5.x-dev].
    - behat/mink-extension v1.3.2 requires behat/behat ~2.5.0 -> satisfiable by behat/behat[2.5.x-dev].
    - behat/mink-extension v1.3.3 requires behat/behat ~2.5.0 -> satisfiable by behat/behat[2.5.x-dev].
    - Conclusion: don't install behat/behat 2.5.x-dev
Installation failed, reverting ./composer.json to its original content.

**Comment by mortola** [comment]
You can use this library as an alternative: https://github.com/mortola/behat-seo-contexts/
